language: php
php:
  - 5.4
  - 5.5

script: vendor/bin/codecept run unit --coverage-xml

before_script:
  - composer install --prefer-source
  - wget https://scrutinizer-ci.com/ocular.phar

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
